import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tomorrow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body
        className={
          "fixed m-0 flex min-h-screen w-screen flex-col items-center justify-between bg-slate-900 text-white"
        }
      >
        {children}
      </body>
    </html>
  );
}
